### ISSUE TITLE
All data lost when container restarted

### ISSUE THREAD

**Issue by deanfourie1** [antedebaas/DMARC-Reports#112]
### Issue Template

**Describe the bug**
When the docker container is stopped,

docker compose down

and then restarted,

docker compose up -d

All data is lost and I am asked to create a new user, start from scratch

**Are you using the Docker image?**
-  Yes

**Database used**
-  MySQL

**Error Messages**
No errors, everything works well, but when the container is restarted, everything is gone, users, reports the whole lot.

**Steps to Reproduce**
Please provide detailed steps to reproduce the problem:
1. run the compose container
2. set everything up via web browser, create users etc, do a initial receive.
3. Stop the container with docker compose down
4. Restart the container with docker compose up -d
5. Browse the webui again, I am prompted to run DB migrations and create a new user, when done and logged in, there are no reports available.

**Expected behavior**
All data to be retained when restarting the container.

**Environment (please complete the following information):**
 - OS: Debian 12
 - Browser: Chrome

**Additional context**
Nothing really, that is it.

**Comment by antedebaas** [comment]
Are you using the provided docker compose file or your own?
And if so you you post your docker compose

**Comment by deanfourie1** [comment]
Hi, thanks, here is docker compose

```
name: dmarc-smtptls-reports
version: "2"
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: dmarc
      MYSQL_USER: dmarcuser
      MYSQL_PASSWORD: Password!100
      MYSQL_ROOT_PASSWORD: Password100!
    ports:
      - 3306
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 6
  web:
    image: antedebaas/dmarc-reports:latest
    ports:
        - 0.0.0.0:8001:8080
    environment:
      TZ: Pacific/Auckland
      DATABASE_TYPE: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_NAME: dmarc
      DATABASE_USER: dmarcuser
      DATABASE_PASSWORD: 
      MAILER_HOST: 
      MAILER_SMTPPORT: 465
      MAILER_IMAPPORT: 993
      MAILER_USER: 
      MAILER_PASSWORD: 
      DELETE_PROCESSED_MAILS: false
      ENABLE_REGISTRATION: false
      MAILCHECK_SCHEDULE: "0 * * * *"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
```
