### ISSUE TITLE
Error on registration - TimeZone issues

### ISSUE THREAD

**Issue by kimdre** [antedebaas/DMARC-Reports#12]
When I try to register my first user I receive an 500 error on the web UI after I click the "Register" button (Error see below).
It seems like the mailer client isn't able to send the registration mail via SMTP (I tried both ports for secure SMTP, 465 and 587)
I also tried different passwords with different lengths and strengths.

My docker-compose.yml
```yaml
name: dmarc-smtptls-reports
version: "2"
services:
  app:
    image: antedebaas/dmarc-reports:latest
    ports:
        - 8087:8080
    environment:
      TZ: Europe/Berlin
      DATABASE_TYPE: mysql
      DATABASE_HOST: db1.prod.<mydomain>
      DATABASE_PORT: 3306
      DATABASE_NAME: dmarcreports
      DATABASE_USER: dmarcreports
      DATABASE_PASSWORD: '<db_password>'
      MAILER_HOST: mail.<mydomain>
      MAILER_SMTPPORT: 587
      MAILER_IMAPPORT: 993
      MAILER_USER: dmarc-reports@<mydomain>
      MAILER_PASSWORD: '<mailer_password>'
    restart: unless-stopped
```

UI Error
```
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
```

Docker Log:
```
NOTICE: PHP message: [critical] Uncaught PHP Exception Symfony\Component\Mailer\Exception\TransportException: "Failed to authenticate on SMTP server with username "dmarc-reports@<mydomain>" using the following authenticators: "LOGIN", "PLAIN". Authenticator "LOGIN" returned "Expected response code "235" but got code "535", with message "535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6".". Authenticator "PLAIN" returned "Expected response code "235" but got code "535", with message "535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6"."." at /var/www/html/vendor/symfony/mailer/Transport/Smtp/EsmtpTransport.php line 225

2023/11/19 22:45:35 [error] 16#16: *7 FastCGI sent in stderr: "PHP message: [critical] Uncaught PHP Exception Symfony\Component\Mailer\Exception\TransportException: "Failed to authenticate on SMTP server with username "dmarc-reports@<mydomain>" using the following authenticators: "LOGIN", "PLAIN". Authenticator "LOGIN" returned "Expected response code "235" but got code "535", with message "535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6".". Authenticator "PLAIN" returned "Expected response code "235" but got code "535", with message "535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6"."." at /var/www/html/vendor/symfony/mailer/Transport/Smtp/EsmtpTransport.php line 225" while reading response header from upstream, client: 172.26.0.1, server: _, request: "POST /register HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "dmarc.<mydomain>", referrer: "https://dmarc.<mydomain>/register"
```
