### ISSUE TITLE
Cannot create the attachments directory

### ISSUE THREAD

**Issue by tobsowo** [antedebaas/DMARC-Reports#51]
I am unable to retrieve mail and this is what I found in logs, can someone please share how I can get this resolved with docker installation?

```NOTICE: PHP message: [critical] Error thrown while running command "app:getreportsfrommailbox". Message: "Cannot create the attachments directory "/var/www/html/var/imap/attachments""```

**Comment by tobsowo** [comment]
`2024/03/08 06:22:49 [error] 14#14: *1948 FastCGI sent in stderr: "PHP message: [critical] Error thrown while running command "app:getreportsfrommailbox". Message: "Cannot create the attachments directory "/var/www/html/var/imap/attachments""" while reading response header from upstream, client: 192.168.1.2, server: _, request: "GET /reports/checkmailnow HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm.sock:", host: "report.example.com", referrer: "https://report.example.com/"
NOTICE: PHP message: [critical] Error thrown while running command "app:getreportsfrommailbox". Message: "Cannot create the attachments directory "/var/www/html/var/imap/attachments""
[critical] Error thrown while running command "app:getreportsfrommailbox". Message: "["TLS\/SSL failure for mail.example.com: SSL negotiation failed"]"
In Imap.php line 712:
  ["TLS\/SSL failure for mail.bluespace.com.ng: SSL negotiation failed"]  
app:getreportsfrommailbox`

**Comment by bundyland** [comment]
I'm not an expert in Docker, but it looks for me that there is an SSL error between your host and the mail host.
How does your docker compose file look like? It should look like this:

environment:
      MAILER_HOST: my.mailhost.de
      MAILER_SMTPPORT: 587
      MAILER_IMAPPORT: 993
      MAILER_USER: my@mailbox.de
      MAILER_PASSWORD: myverystrongepassword

So maybe you should try different ports like 587 or 465 for smtp and 143 or 993 for imap. All depends on your mail host of course.

**Comment by tobsowo** [comment]
While troubleshooting I changed the SSL to a less secure reason for that.

This is what I have now
```
app:getreportsfrommailbox
  server: [CLOSED] IMAP connection broken (server response)"]                  
  ["IMAP SERVER BUG (invalid challenge): \"\"","Can not authenticate to IMAP   
In Imap.php line 712:
[critical] Error thrown while running command "app:getreportsfrommailbox". Message: "["IMAP SERVER BUG (invalid challenge): \"\"","Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (server response)"]"
                                                                               
NOTICE: PHP message: [critical] Error thrown while running command "app:getreportsfrommailbox". Message: "["IMAP SERVER BUG (invalid challenge): \"\"","Can not authenticate to IMAP server: [CLOSED] IMAP connection broken (server response)"]"
```

**Comment by tobsowo** [comment]
This is my docker compose
```
name: dmarc-smtptls-reports
version: "2"
services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_DATABASE: dmarcreports
      MYSQL_USER: dmarc
      MYSQL_PASSWORD: bE5^
      MYSQL_ROOT_PASSWORD: 4dhtf
      
    ports:
      - 3306
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 6
      
  web:
    image: antedebaas/dmarc-reports:latest
    ports:
        - 0.0.0.0:8080:8080
    environment:
      DATABASE_TYPE: mysql
      DATABASE_HOST: db
      DATABASE_PORT: 3306 
      DATABASE_NAME: dmarc
      DATABASE_USER: dmarc
      DATABASE_PASSWORD: bE5
      MAILER_HOST: mail.bl
      MAILER_SMTPPORT: 587
      MAILER_IMAPPORT: 993
      MAILER_USER: web
      MAILER_PASSWORD: PA
      DELETE_PROCESSED_MAILS: false
      ENABLE_REGISTRATION: false
      MAILCHECK_SCHEDULE: "15 * * * *"
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
```
